### ISSUE TITLE
Packaging github.com/spkg/bom [#924259]

### ISSUE THREAD

**Issue by jmkim** [jesseduffield/lazygit-debian#1]
@dawidd6 Would you please package the first one on [the package tracker](https://github.com/jesseduffield/lazygit-debian/wiki/Package-tracker)? It is `github.com/spkg/bom`.

For new packages, we have to follow the "new workflow" from Go Packaging Team, please read and follow https://go-team.pages.debian.net/workflow-changes.html

Thank you!

**Comment by dawidd6** [comment]
Only RFS remains. Should I do it now or after we package everything? @jmkim

**Comment by jmkim** [comment]
Let's do now for getting a fast feedback :)

This period is a soft freeze, so our package will not getting into unstable until 12/4 (buster release). Anyway let's send a RFS mail one by one when we finish each packages.

**Comment by dawidd6** [comment]
Now only wait for a sponsor to upload package and this can be closed.

**Comment by jmkim** [comment]
I read the review from Reinhard Tartler, and I also tried building your package.

Here is my reviews:

About tags:
- If upstream does not have version tag or [upstream source should modified](https://wiki.debian.org/DebianMentorsFaq#What_does_.2BIBw-dfsg.2BIB0_or_.2BIBw-ds.2BIB0_in_the_version_string_mean.3F):
    - Create a tag to specify the version. Format is `upstream/<UPSTREAM_VERSION>`.

- If upstream does have version tag:
    - Use upstream's version.
    - Edit `debian/gbp.conf` and add `upstream-tag` rule in `[DEFAULT]` section:
        ```
        [DEFAULT]
        upstream-tag = v%(version)s
        ```
    - See also [DEP-14](https://dep-team.pages.debian.net/deps/dep14/), **Version mangling**.

- For debian releases, DD will add the tag `debian/<DEBIAN_VERSION>` before upload or during review. So do not tag `debian/<DEBIAN_VERSION>` ourselves.

While writing this, you already fixed all. Great work! :D

**Comment by dawidd6** [comment]
Dang. I've already made 2 debian tags.

**Comment by jmkim** [comment]
No problem, sponsor will remove. If not, request to him :D

**Comment by dawidd6** [comment]
Reinhard said he uploaded it. Where will it be available in archive?

**Comment by jmkim** [comment]
`ftp-master.debian.org`. You can track your package 1~2 days later at https://qa.debian.org/developer.php?email=dawidd0811%40gmail.com

**Comment by jmkim** [comment]
As the package uploaded, this issue can be closed. If there is a problem, let's open again. Congratulations! :tada: :tada:
