### ISSUE TITLE
Packaging github.com/hashicorp/go-safetemp [#924347]

### ISSUE THREAD

**Issue by jmkim** [jesseduffield/lazygit-debian#12]

**Comment by jmkim** [comment]
Hello, @nightwarrior-xxx! Would you please packaging this?

**Comment by nightwarriorftw** [comment]
@jmkim Yes

**Comment by jmkim** [comment]
@nightwarrior-xxx please see also [Wiki of this repository](https://github.com/jesseduffield/lazygit-debian/wiki). There is [a package tracker (with dependency graph)](https://github.com/jesseduffield/lazygit-debian/wiki/Package-tracker) and [a guide for packaging](https://github.com/jesseduffield/lazygit-debian/wiki/Packaging-guide-for-newcomer).

Update the package tracker there yourself while packaging. Thank you and welcome!

**Comment by nightwarriorftw** [comment]
Do I RFS now, becuase I am done with packaging it or we will do it once all are completed.
[It's here](https://salsa.debian.org/go-team/packages/golang-github-hashicorp-go-safetemp/tree/master/debian)

**Comment by jmkim** [comment]
Let's do now for getting a fast feedback :)

As you know, this period is a soft freeze, so our package will not getting into unstable until 12/4 (buster release). Anyway let's send a RFS mail one by one when we finish each packages.

**Comment by jmkim** [comment]
@nightwarrior-xxx  Before then, can I review your package first?

**Comment by jmkim** [comment]
I thought that you already heard about "new workflow" from Go Packaging Team. For new packages, we have to follow the "new workflow", please read and follow [1].

[1] https://go-team.pages.debian.net/workflow-changes.html

For applying the "new workflow" to your work, I wrote some instruction on wiki of this repo [2]. Check and try.

[2] https://github.com/jesseduffield/lazygit-debian/wiki/Packaging-guide-for-newcomer

Thank you!

**Comment by nightwarriorftw** [comment]
@jmkim Yes, you can review sensai after all you are the only one experienced here .

**Comment by jmkim** [comment]
@nightwarrior-xxx [The repo](https://salsa.debian.org/go-team/packages/golang-github-hashicorp-go-safetemp/tree/master) doesn't adopted new workflow yet, are you facing some problem with applying it?

**Comment by nightwarriorftw** [comment]
Will ask you doubts on IRC if any . Currently reading new workflow. Will be back in form soon.
