### ISSUE TITLE
Updating github.com/OpenPeeDeeP/xdg to 1.0.0

### ISSUE THREAD

**Issue by jmkim** [jesseduffield/lazygit-debian#37]
https://salsa.debian.org/go-team/packages/golang-github-openpeedeep-xdg

**Comment by AravindIM** [comment]
I'm interested in packaging this. Please let me know if you have received the ITP for it.

**Comment by AravindIM** [comment]
ITP: https://bugs.debian.org/1052341

**Comment by AravindIM** [comment]
I'm sorry but the package already exists on salsa:
https://salsa.debian.org/go-team/packages/golang-github-openpeedeep-xdg

**Comment by AravindIM** [comment]
ITP has been closed as duplicate

**Comment by jmkim** [comment]
@dawidd6 o/
@AravindIM [found the package was made by you triple years ago](https://salsa.debian.org/go-team/packages/golang-github-openpeedeep-xdg), can we update it to the latest `1.0.0`?

**Comment by AravindIM** [comment]
It's made by another upstream maintainer Jermer Vernooij

**Comment by jmkim** [comment]
> It's made by another upstream maintainer Jermer Vernooij

@AravindIM no, his upload was team-upload, for applying Janitor’s suggestions.
You can see [the package changelog](https://salsa.debian.org/go-team/packages/golang-github-openpeedeep-xdg/-/blob/debian/sid/debian/changelog)

**Comment by dawidd6** [comment]
I think you should be able to update the repository if you are part of the Go team on salsa.

**Comment by AravindIM** [comment]
Upstream version has been updated to 1.0.0 on salsa.Packaging has been tested locally with sbuild and also it passed the salsa ci test. I would need assistance with mailing an RFS.

**Comment by AravindIM** [comment]
I have sent the RFS:
https://lists.debian.org/debian-go/2023/10/msg00015.html

**Comment by AravindIM** [comment]
Package has been accepted by FTP Master. New version available in sid:
https://packages.debian.org/sid/golang-github-openpeedeep-xdg-dev
