### ISSUE TITLE
Packaging connectrpc.com/connect [#1055741]

### ISSUE THREAD

**Issue by jmkim** [jesseduffield/lazygit-debian#41]
https://salsa.debian.org/go-team/packages/golang-connectrpc-connect

**Comment by jmkim** [comment]
Welcome welcome, @Maytha8 \o/

IFS Sent : https://bugs.debian.org/1055741

**Comment by Maytha8** [comment]
@jmkim 
RFS sent: https://bugs.debian.org/1055975

**Comment by Maytha8** [comment]
Uploaded, currently in NEW queue, awaiting approval from FTP masters.

**Comment by Maytha8** [comment]
@jmkim Approved, now in unstable. Will get it migrated to testing ASAP. Could you please close this issue as done?
